name: Invite CI
on:
  issues:
    types: [opened, edited]
jobs:
  invite:
    name: Send invites
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build TypeScript
        run: npm run build
      - name: Run script
        run: npm run start
